id: I60C15467
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-15 07:37:02.864853+00:00
last_modified: 2022-12-15 07:37:02.864868+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-058-001
  eft-text-version: 1.2.1 2020
  title: Toh_152-The_Questions_of_Sagaramati-v2
bases:
  7E7E:
    source_metadata: null
    order: 1
    base_file: 7E7E.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
